---
- hosts: postgre

  tasks:

  # Импортируем константы
  - name: Import vars
    include_vars: vars/vaulted_vars.yml

  # Устанавливаем необходимый репозиторий для установки
  - name: Install PostgreSQL repo
    yum: name=https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/pgdg-centos96-9.6-3.noarch.rpm state=present 

  # Установка PostgreSQL и включение в автозагрузку  
  - name: Install PostgreSQL
    yum: name="{{ item }}" state=latest update_cache=yes enablerepo=pgdg96
    with_items:
      - "postgresql96"
      - "postgresql96-server"
      - "postgresql96-contrib"
      - "postgresql96-libs"
      - "postgresql96-devel"
      - python-psycopg2
      - cronie-anacron
      - cronie
      - crontabs   
                                
  # Остановка службы PostgreSQL								 
  - name: PostgreSQL service stop    
    service:
       name: 'postgresql-9.6'
       state: stopped
      
  # Delete data PostgreSQL	
  - name: Delete data PostgreSQL
    file: path="{{item}}" state=absent
    with_items:
      - /var/lib/pgsql/9.6/1
      - /var/lib/pgsql/9.6/1/data
      - /var/lib/pgsql/9.6/2
      - /var/lib/pgsql/9.6/2/data

  # Инициализируем наш PostgreSQL	
  - name: Create dir
    command: "{{item}}"
    with_items:
      - "mkdir /var/lib/pgsql/9.6/1"
      - "mkdir /var/lib/pgsql/9.6/1/data"
      - "mkdir /var/lib/pgsql/9.6/2"
      - "mkdir /var/lib/pgsql/9.6/2/data"

  # Инициализируем наш PostgreSQL	
  - name: Init data cluster 1
    command:  "{{item}}"
    with_items:
      - "/usr/pgsql-9.6/bin/postgresql96-setup initdb /var/lib/pgsql/9.6/1/data"
      - "/usr/pgsql-9.6/bin/postgresql96-setup initdb /var/lib/pgsql/9.6/2/data"

  # Инициализируем наш PostgreSQL	
  - name: Start data cluster 1
    command: "{{item}}"
    with_items:
      - 'pg_ctl -D /var/lib/pgsql/9.6/1/data -o "-p 6666" -l /var/lib/pgsql/9.6/1/logdb1 start'
      - 'pg_ctl -D /var/lib/pgsql/9.6/2/data -o "-p 7777" -l /var/lib/pgsql/9.6/2/logdb2 start'