---
- hosts: postgre
     
  tasks:
  - name: Install PostgreSQL repo
    yum: name=https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/pgdg-centos96-9.6-3.noarch.rpm state=present    
  - name: Install PostgreSQL
    yum: name="{{ item }}" state=latest
    update_cache: yes
    enablerepo: "pgdg96"
    with_items:
      - "postgresql96"
      - "postgresql96-server"
      - "postgresql96-contrib"
      - "postgresql96-libs"
      - "postgresql96-devel"
      - python-psycopg2
      - cronie-anacron
      - cronie
      - crontabs   
                                  
- hosts: postgre
    
  tasks:
  - service:
    name: postgresql-9.6
    state: stopped
      
  - name: create data cluster
#    command: service postgresql-9.6 initdb
    command: /usr/pgsql-9.6/bin/postgresql96-setup initdb
    
                                                                                                                