---
- hosts: postgre

  tasks:

  # Импортируем константы
  - name: Import vars
    include_vars: vars/vaulted_vars.yml

  # Импортируем установку и бутылки
  - name: Import install and bottle
    include: postgre-install-bottle.yml

  # Enable PostgreSQL	
  - name: Enable cluster
    command: systemctl enable postgresql-9.6
  
  # Запускаем службы PostgreSQL	  
#  - name: PostgreSQL service start    
#    command: systemctl start postgresql-9.6

  # Импортируем добавление пользователей в систему
  - name: Import add users in system
    include: postgre-addsysuser.yml

  # Импортируем добавление пользователей и БД
  - name: Import add users and db
    include: postgre-adddb-adduserdb.yml

  # Импортируем добавление пользователей и БД
  - name: Import add users and db
    include: postgre-change-conf.yml

#  handlers:
#    # перечитываем конфигурацию postgresql
#  - name: reload postgres
#    sudo: yes
#    action: service name=postgresql-9.6 state=reloaded

    # перезагружаем postgresql
#  - name: restart postgres
#    sudo: yes
#    command: systemctl restart postgresql-9.6
 
    # enable postgresql
#  - name: enable postgres
#    sudo: yes
#    action: systemctl enable postgresql-9.6