---
- hosts: postgre
    
  tasks:
  - name: Import Postgresql96 repo
    yum: name=https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/pgdg-centos96-9.6-3.noarch.rpm state=present
    tags: patroni
    when: install is defined
      
  - name: Install PGsql96
    yum: name={{ item }} state=latest
    tags: patroni
    with_items:
      - postgresql96
      - postgresql96-contrib
      - postgresql96-server
      - python-psycopg2
      - repmgr96
    when: install is defined
                                  
- hosts: postgre
    
  tasks:
  - service:
    name: postgresql-9.6
    state: stopped
      
  - name: create data cluster
    command: service postgresql-9.6 initdb
                                                                                                            