---
- hosts: postgre
     
  tasks:
  - name: Install PostgreSQL repo
    yum: name=https://download.postgresql.org/pub/repos/yum/9.6/redhat/rhel-7-x86_64/pgdg-centos96-9.6-3.noarch.rpm state=present    
  
  - name: Install PostgreSQL
    yum: name="{{ item }}" state=latest
    update_cache: yes
    enablerepo: "pgdg96"
    with_items:
      - "postgresql96"
      - "postgresql96-server"
      - "postgresql96-contrib"
      - "postgresql96-libs"
      - "postgresql96-devel"
      - python-psycopg2
      - cronie-anacron
      - cronie
      - crontabs   
                                  
  - name: PostgreSQL service stop    
    service:
       name: 'postgresql-9.6'
       state: stopped
      
  - name: Create data cluster
    command: /usr/pgsql-9.6/bin/postgresql96-setup initdb

  - name: Enable PostgreSQL
    service: 
       name: 'postgresql-9.6'
       enabled: yes
       state: started
       daemon_reload: yes
  
  - name: PostgreSQL service start    
    service:
       name: 'postgresql-9.6'
       state: started

  - name: Create db1 PostgreSQL
    become: yes
    become_user: postgres
    postgresql_db: 
      name: pgmax1
      encoding: UTF-8
      state: present

  - name: Create db2 PostgreSQL
    become: yes
    become_user: postgres
    postgresql_db: 
      name: pgmax2
      encoding: UTF-8
      state: present
                                              
  - name: Create user1 PostgreSQL
    become: yes
    become_user: postgres
    postgresql_user:
      name: upg1
      password: 078385
      db: pgmax1
  
  - name: Ensure we have access from the new user
    become: yes
    become_user: postgres
    postgresql_privs:
      db: pgmax1
      role: upg1
      objs: ALL_IN_SCHEMA
      privs: "ALL"
  
  - name: Create user2 PostgreSQL
    become: yes
    become_user: postgres
    postgresql_user:
      name: upg2
      password: 078385
      db: pgmax2

  - name: Ensure we have access from the new user
    become: yes
    become_user: postgres
    postgresql_privs:
      db: pgmax2
      role: superuser
      objs: ALL_IN_SCHEMA
      privs: "ALL"