---
- hosts: postgre

  tasks:

  # Импортируем константы
  - name: Import vars
    include_vars: vars/vaulted_vars.yml

  # Импортируем установку и бутылки
  - name: Import install and bottle
    include: postgre-install-bottle.yml

  # Enable PostgreSQL	
  - name: Enable cluster
    command: systemctl enable postgresql-9.6
  
  # Импортируем добавление пользователей в систему
  - name: Import add users in system
    include: postgre-addsysuser.yml

  # Импортируем добавление пользователей и БД
  - name: Import add users and db
    include: postgre-adddb-adduserdb.yml

  # Импортируем добавление пользователей и БД
  - name: Import add users and db
    include: postgre-change-conf.yml

  # Проверка портов 6666 и 7777. Что-то висит на них?
  - name: Check ports 6666, 7777
    include: postgre-check-ports.yml

#  handlers:
#    # перечитываем конфигурацию postgresql
#  - name: reload postgres
#    become: yes 
#    become_user: postgres
#    become_method: sudo
#    command: /usr/pgsql-9.6/bin/pg_ctl -D /var/lib/pgsql/9.6/1/data -o "-p 6666" reload
     
    # перезагружаем postgresql
#  - name: restart postgres
#    become: yes 
#    become_user: postgres
#    become_method: sudo
#    command: /usr/pgsql-9.6/bin/pg_ctl -D /var/lib/pgsql/9.6/1/data -o "-p 6666" restart